// Generated by CoffeeScript 1.3.3
(function() {
  var TempoDBClient, net, request, tempodb;

  request = require('request');

  net = require('net');

  TempoDBClient = require('tempodb').TempoDBClient;

  tempodb = new TempoDBClient('api-key', 'api-secret');

}).call(this);
